# Multiple files with `pandas`

In [2]:
import numpy as np
import pandas as pd
import matplotlib

## Merge Practice

In [3]:
a_df = pd.DataFrame({
    'Country': ['Germany', 'France', 'Belgium', 'Finland'],
    'Population (M)': [82.8, 67.2, 11.4, 5.5],
    'Capital': ['Berlin', 'Paris', 'Brussels', 'Helsinki']
})
a_df

   Country  Population (M)   Capital
0  Germany            82.8    Berlin
1   France            67.2     Paris
2  Belgium            11.4  Brussels
3  Finland             5.5  Helsinki

In [4]:
b_df = pd.DataFrame({
    'Country': ['Germany', 'France', 'Belgium', 'Canada'],
    'HDI': [0.936, 0.901, 0.916, 0.926]
})
b_df

   Country    HDI
0  Germany  0.936
1   France  0.901
2  Belgium  0.916
3   Canada  0.926

### Inner Merge Practice

#### Check your code

In [5]:
inner_merged_df = pd.merge(a_df, b_df, on='Country', how='inner')
inner_merged_df

   Country  Population (M)   Capital    HDI
0  Germany            82.8    Berlin  0.936
1   France            67.2     Paris  0.901
2  Belgium            11.4  Brussels  0.916

In [6]:
from nbresult import ChallengeResult

result = ChallengeResult(
    'inner_merge',
    inner_merged_shape=inner_merged_df.shape,
    inner_merged_nulls=sum(inner_merged_df.isnull().sum()),
)
result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/moha/.pyenv/versions/3.12.9/envs/lewagon/bin/python
cachedir: .pytest_cache
rootdir: /home/moha/code/Mohammed90911/02-Data-Toolkit/01-Data-Analysis/data-multiple-files-with-pandas
configfile: pytest.ini
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 2 items

test_inner_merge.py::TestInnerMerge::test_inner_merged_nulls PASSED      [ 50%]
test_inner_merge.py::TestInnerMerge::test_inner_merged_shape PASSED      [100%]

============================== 2 passed in 0.02s ===============================


💯 You can commit your code:

git add tests/inner_merge.pickle

git commit -m 'Completed inner_merge step'

git push origin master

### Left Merge Practice

#### Check your code

In [7]:
left_merged_df = pd.merge(a_df, b_df, on='Country', how='left')
left_merged_df

   Country  Population (M)   Capital    HDI
0  Germany            82.8    Berlin  0.936
1   France            67.2     Paris  0.901
2  Belgium            11.4  Brussels  0.916
3  Finland             5.5  Helsinki    NaN

In [8]:
from nbresult import ChallengeResult

result = ChallengeResult(
    'left_merge',
    left_merged_shape=left_merged_df.shape,
    left_merged_nulls=sum(left_merged_df.isnull().sum()),
)
result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/moha/.pyenv/versions/3.12.9/envs/lewagon/bin/python
cachedir: .pytest_cache
rootdir: /home/moha/code/Mohammed90911/02-Data-Toolkit/01-Data-Analysis/data-multiple-files-with-pandas
configfile: pytest.ini
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 2 items

test_left_merge.py::TestLeftMerge::test_left_merged_df_shape PASSED      [ 50%]
test_left_merge.py::TestLeftMerge::test_left_merged_nulls PASSED         [100%]

============================== 2 passed in 0.03s ===============================


💯 You can commit your code:

git add tests/left_merge.pickle

git commit -m 'Completed left_merge step'

git push origin master

### Right Merge Practice

#### Check your code

In [9]:
right_merged_df = pd.merge(a_df, b_df, on='Country', how='right')
right_merged_df

   Country  Population (M)   Capital    HDI
0  Germany            82.8    Berlin  0.936
1   France            67.2     Paris  0.901
2  Belgium            11.4  Brussels  0.916
3   Canada             NaN       NaN  0.926

In [10]:
from nbresult import ChallengeResult

result = ChallengeResult(
    'right_merge',
    right_merged_shape=right_merged_df.shape,
    right_merged_nulls=sum(right_merged_df.isnull().sum()),
)
result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/moha/.pyenv/versions/3.12.9/envs/lewagon/bin/python
cachedir: .pytest_cache
rootdir: /home/moha/code/Mohammed90911/02-Data-Toolkit/01-Data-Analysis/data-multiple-files-with-pandas
configfile: pytest.ini
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 2 items

test_right_merge.py::TestRightMerge::test_right_merged_df_shape PASSED   [ 50%]
test_right_merge.py::TestRightMerge::test_right_merged_nulls PASSED      [100%]

============================== 2 passed in 0.03s ===============================


💯 You can commit your code:

git add tests/right_merge.pickle

git commit -m 'Completed right_merge step'

git push origin master

### Outer Merge Practice

#### Check your code

In [11]:
outer_merged_df = pd.merge(a_df, b_df, on='Country', how='outer')
outer_merged_df

   Country  Population (M)   Capital    HDI
0  Belgium            11.4  Brussels  0.916
1   Canada             NaN       NaN  0.926
2  Finland             5.5  Helsinki    NaN
3   France            67.2     Paris  0.901
4  Germany            82.8    Berlin  0.936

In [12]:
from nbresult import ChallengeResult

result = ChallengeResult(
    'outer_merge',
    outer_merged_shape=outer_merged_df.shape,
    outer_merged_nulls=sum(outer_merged_df.isnull().sum()),
)
result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/moha/.pyenv/versions/3.12.9/envs/lewagon/bin/python
cachedir: .pytest_cache
rootdir: /home/moha/code/Mohammed90911/02-Data-Toolkit/01-Data-Analysis/data-multiple-files-with-pandas
configfile: pytest.ini
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 2 items

test_outer_merge.py::TestOuterMerge::test_outer_merged_df_shape PASSED   [ 50%]
test_outer_merge.py::TestOuterMerge::test_outer_merged_nulls PASSED      [100%]

============================== 2 passed in 0.03s ===============================


💯 You can commit your code:

git add tests/outer_merge.pickle

git commit -m 'Completed outer_merge step'

git push origin master

## Join Practice

In [13]:
aa_df = a_df.set_index("Country")
aa_df

         Population (M)   Capital
Country
Germany            82.8    Berlin
France             67.2     Paris
Belgium            11.4  Brussels
Finland             5.5  Helsinki

In [14]:
bb_df = b_df.set_index("Country")
bb_df

           HDI
Country
Germany  0.936
France   0.901
Belgium  0.916
Canada   0.926

In [15]:
aa_df.join(bb_df)

         Population (M)   Capital    HDI
Country
Germany            82.8    Berlin  0.936
France             67.2     Paris  0.901
Belgium            11.4  Brussels  0.916
Finland             5.5  Helsinki    NaN

In [16]:
aa_df.join(bb_df, how='inner')
aa_df.join(bb_df, how='right')
aa_df.join(bb_df, how='outer')

         Population (M)   Capital    HDI
Country
Belgium            11.4  Brussels  0.916
Canada              NaN       NaN  0.926
Finland             5.5  Helsinki    NaN
France             67.2     Paris  0.901
Germany            82.8    Berlin  0.936

## Concat Practice

In [17]:
concat_df = pd.concat([a_df, b_df], axis="index", sort=False)
concat_df

   Country  Population (M)   Capital    HDI
0  Germany            82.8    Berlin    NaN
1   France            67.2     Paris    NaN
2  Belgium            11.4  Brussels    NaN
3  Finland             5.5  Helsinki    NaN
0  Germany             NaN       NaN  0.936
1   France             NaN       NaN  0.901
2  Belgium             NaN       NaN  0.916
3   Canada             NaN       NaN  0.926

## Olympic Sports and Medals, 1896-2014

### Combining The Data

In [19]:
countries_df = pd.read_csv('dictionary.csv')
summer_df = pd.read_csv('summer.csv')
winter_df = pd.read_csv('winter.csv')

summer_df = summer_df.rename(columns={'Country': 'Code'})
winter_df = winter_df.rename(columns={'Country': 'Code'})

summer_countries_df = pd.merge(countries_df, summer_df, on='Code', how='inner')
summer_countries_df['Season'] = 'Summer'

winter_countries_df = pd.merge(countries_df, winter_df, on='Code', how='inner')
winter_countries_df['Season'] = 'Winter'

all_df = pd.concat([summer_countries_df, winter_countries_df], axis='index')
all_df.head(3)

,Country,Code,Population,GDP per Capita,Year,City,Sport,Discipline,Athlete,Gender,Event,Medal,Season
0,Afghanistan,AFG,32526562.0,594.323081,2008,Beijing,Taekwondo,Taekwondo,"NIKPAI, Rohullah",Men,- 58 KG,Bronze,Summer
1,Afghanistan,AFG,32526562.0,594.323081,2012,London,Taekwondo,Taekwondo,"NIKPAI, Rohullah",Men,58 - 68 KG,Bronze,Summer
2,Algeria,ALG,39666519.0,4206.031232,1984,Los Angeles,Boxing,Boxing,"ZAOUI, Mohamed",Men,71-75KG,Bronze,Summer

In [20]:
from nbresult import ChallengeResult

result = ChallengeResult(
    'all_df', all_df_shape=all_df.shape, all_df_columns=set(all_df.columns)
)
result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/moha/.pyenv/versions/3.12.9/envs/lewagon/bin/python
cachedir: .pytest_cache
rootdir: /home/moha/code/Mohammed90911/02-Data-Toolkit/01-Data-Analysis/data-multiple-files-with-pandas
configfile: pytest.ini
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 2 items

test_all_df.py::TestAllDf::test_all_df_columns PASSED                    [ 50%]
test_all_df.py::TestAllDf::test_all_df_shape PASSED                      [100%]

============================== 2 passed in 0.03s ===============================


💯 You can commit your code:

git add tests/all_df.pickle

git commit -m 'Completed all_df step'

git push origin master

### Top Countries Analysis

In [23]:
since_1984 = all_df[all_df['Year'] >= 1984]

top_10_df = (
    since_1984.groupby('Country')[['Medal']]
    .count()
    .rename(columns={'Medal': 'Medal Count'})
    .sort_values(by='Medal Count', ascending=False)
    .head(10)
)

top_10_df

               Medal Count
Country
United States         2472
Germany               1112
Russia                1031
Australia              891
China                  889
Canada                 801
Italy                  632
Korea, South           587
France                 587
Netherlands            563

In [24]:
from nbresult import ChallengeResult

result = ChallengeResult(
    'olympic_games',
    top_country_1=top_10_df.iloc[0]['Medal Count'],
    top_country_10=top_10_df.iloc[9]['Medal Count'],
)
result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/moha/.pyenv/versions/3.12.9/envs/lewagon/bin/python
cachedir: .pytest_cache
rootdir: /home/moha/code/Mohammed90911/02-Data-Toolkit/01-Data-Analysis/data-multiple-files-with-pandas
configfile: pytest.ini
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 1 item

test_olympic_games.py::TestOlympicGames::test_top_10_countries_medals PASSED [100%]

============================== 1 passed in 0.30s ===============================


💯 You can commit your code:

git add tests/olympic_games.pickle

git commit -m 'Completed olympic_games step'

git push origin master

In [25]:

season_df = (
    since_1984.groupby(['Country', 'Season'])[['Medal']].count().unstack()
)

season_df.columns = season_df.columns.droplevel(0)
season_df = season_df.fillna(0)

season_df['Total'] = season_df['Summer'] + season_df['Winter']
top_10_season_df = (
    season_df.sort_values(by='Total', ascending=False)
    .head(10)[['Summer', 'Winter', 'Total']]
)

top_10_season_df

Season         Summer  Winter   Total
Country
United States  2087.0   385.0  2472.0
Germany         785.0   327.0  1112.0
Russia          768.0   263.0  1031.0
Australia       876.0    15.0   891.0
China           807.0    82.0   889.0
Canada          341.0   460.0   801.0
Italy           486.0   146.0   632.0
Korea, South    500.0    87.0   587.0
France          482.0   105.0   587.0
Netherlands     476.0    87.0   563.0

In [26]:
from nbresult import ChallengeResult

result = ChallengeResult(
    'olympic_games_season',
    top_country_season_shape=top_10_season_df.shape,
    top_country_1_summer=top_10_season_df.iloc[0]['Summer'],
    top_country_10_winter=top_10_season_df.iloc[9]['Winter'],
)
result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/moha/.pyenv/versions/3.12.9/envs/lewagon/bin/python
cachedir: .pytest_cache
rootdir: /home/moha/code/Mohammed90911/02-Data-Toolkit/01-Data-Analysis/data-multiple-files-with-pandas
configfile: pytest.ini
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 3 items

test_olympic_games_season.py::TestOlympicGamesSeason::test_top_10_countries_shape PASSED [ 33%]
test_olympic_games_season.py::TestOlympicGamesSeason::test_top_10_countries_summer PASSED [ 66%]
test_olympic_games_season.py::TestOlympicGamesSeason::test_top_10_countries_winter PASSED [100%]

============================== 3 passed in 0.23s ===============================


💯 You can commit your code:

git add tests/olympic_games_season.pickle

git commit -m 'Completed olympic_games_season step'

git push origin master

In [27]:
events_df = since_1984.drop_duplicates(
    subset=['Year', 'Season', 'City', 'Sport', 'Discipline', 'Event', 'Country', 'Medal']
)

top_10_events_df = (
    events_df.groupby('Country')[['Event']]
    .count()
    .rename(columns={'Event': 'Event Count'})
    .sort_values(by='Event Count', ascending=False)
    .head(10)
)

top_10_events_df

                Event Count
Country
United States           949
Germany                 512
Russia                  498
China                   479
France                  325
Italy                   304
Australia               292
Canada                  276
United Kingdom          271
Korea, South            259

In [28]:
from nbresult import ChallengeResult

result = ChallengeResult(
    'olympic_games_event',
    top_country_event_shape=top_10_events_df.shape,
    top_country_1_event=top_10_events_df.iloc[0]['Event Count'],
    top_country_10_event=top_10_events_df.iloc[9]['Event Count'],
)
result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/moha/.pyenv/versions/3.12.9/envs/lewagon/bin/python
cachedir: .pytest_cache
rootdir: /home/moha/code/Mohammed90911/02-Data-Toolkit/01-Data-Analysis/data-multiple-files-with-pandas
configfile: pytest.ini
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 3 items

test_olympic_games_event.py::TestOlympicGamesEvent::test_top_10_events_shape PASSED [ 33%]
test_olympic_games_event.py::TestOlympicGamesEvent::test_top_events_1 PASSED [ 66%]
test_olympic_games_event.py::TestOlympicGamesEvent::test_top_events_10 PASSED [100%]

============================== 3 passed in 0.16s ===============================


💯 You can commit your code:

git add tests/olympic_games_event.pickle

git commit -m 'Completed olympic_games_event step'

git push origin master

In [29]:
top_10_combined = (
    pd.concat([top_10_df, top_10_events_df], axis=1)
    .dropna(subset=['Medal Count', 'Event Count'], how='all')
    .sort_values(by='Medal Count', ascending=False)
)

top_10_combined

                Medal Count  Event Count
Country
United States        2472.0        949.0
Germany              1112.0        512.0
Russia               1031.0        498.0
Australia             891.0        292.0
China                 889.0        479.0
Canada                801.0        276.0
Italy                 632.0        304.0
Korea, South          587.0        259.0
France                587.0        325.0
Netherlands           563.0          NaN
United Kingdom          NaN        271.0

In [30]:
from nbresult import ChallengeResult

result = ChallengeResult(
    'olympic_games_combined',
    top_combined_shape=top_10_combined.shape,
    top_combined_1_event=top_10_combined.iloc[0]['Event Count'],
    top_combined_1_medal=top_10_combined.iloc[0]['Medal Count'],
    top_combined_10_event=top_10_combined.iloc[9]['Event Count'],
    top_combined_10_medal=top_10_combined.iloc[9]['Medal Count'],
)
result.write()
print(result.check())

============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/moha/.pyenv/versions/3.12.9/envs/lewagon/bin/python
cachedir: .pytest_cache
rootdir: /home/moha/code/Mohammed90911/02-Data-Toolkit/01-Data-Analysis/data-multiple-files-with-pandas
configfile: pytest.ini
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 3 items

test_olympic_games_combined.py::TestOlympicGamesCombined::test_combined_1 PASSED [ 33%]
test_olympic_games_combined.py::TestOlympicGamesCombined::test_combined_10 PASSED [ 66%]
test_olympic_games_combined.py::TestOlympicGamesCombined::test_top_10_combined_shape PASSED [100%]

============================== 3 passed in 0.21s ===============================


💯 You can commit your code:

git add tests/olympic_games_combined.pickle

git commit -m 'Completed olympic_games_combined step'

git push origin master